#!/usr/bin/env python3
"""Builds assets/header.svg: the animated name banner for this profile.

  - the name: each letter fades in one after another, then an aurora
    gradient (teal, indigo, pink) keeps flowing through it;
  - the roles line: a typewriter that types a role, holds it, deletes it
    with backspaces and types the next, cursor in step with every key.

GitHub shows SVGs as images: no scripts and no web fonts. So the fonts are
embedded (subsets of Space Grotesk and JetBrains Mono, both OFL, fetched from
Google Fonts with only the characters used), and the typing is CSS: each role
is uncovered by a clip rectangle that grows one character width per step
(steps() timing on a monospace font), and the cursor moves the same way.

    tools/make-header.py fonts/name.woff2 fonts/roles.woff2 > assets/header.svg
"""
import base64
import sys

NAME = "Yash Sawarkar"
ROLES = ["MERN developer", "DevOps & cloud", "exploring GenAI", "building with AI agents"]

W, H = 1200, 300
FONT_PX = 22
CW = FONT_PX * 0.6          # JetBrains Mono advance: 600/1000 em
TYPE_S, ERASE_S = 0.085, 0.04  # seconds per key
HOLD_S, GAP_S = 1.7, 0.45
START_S = 1.6               # roles start after the name has appeared

PROMPT = "> "
# Centred on a typical role, not the longest: a left-anchored line sized
# for "building with AI agents" made the short roles sit far left.
typical = sorted(map(len, ROLES))[len(ROLES) // 2]
x_prompt = (W - (len(PROMPT) + typical) * CW) / 2
x_text = x_prompt + len(PROMPT) * CW
Y_TEXT = 236

# One cycle through every role; times in seconds within the cycle.
segments, t = [], 0.0
for r in ROLES:
    n = len(r)
    typed, held, erased = t + n * TYPE_S, t + n * TYPE_S + HOLD_S, t + n * TYPE_S + HOLD_S + n * ERASE_S
    segments.append((r, t, typed, held, erased))
    t = erased + GAP_S
CYCLE = t


def pct(s):
    return f"{100 * s / CYCLE:.3f}%"


def role_keyframes(i, r, t0, t1, t2, t3):
    """Clip rect for one role: scaleX 0 -> 1 in n steps, hold, 1 -> 0 in n steps."""
    n = len(r)
    kf = [f"0% {{ transform: scaleX(0); }}"]
    if t0 > 0:
        kf.append(f"{pct(t0)} {{ transform: scaleX(0); animation-timing-function: steps({n}, end); }}")
    else:
        kf[0] = f"0% {{ transform: scaleX(0); animation-timing-function: steps({n}, end); }}"
    kf.append(f"{pct(t1)} {{ transform: scaleX(1); animation-timing-function: linear; }}")
    kf.append(f"{pct(t2)} {{ transform: scaleX(1); animation-timing-function: steps({n}, end); }}")
    kf.append(f"{pct(t3)} {{ transform: scaleX(0); }}")
    kf.append("100% { transform: scaleX(0); }")
    return f"@keyframes type{i} {{ {' '.join(kf)} }}"


def cursor_keyframes():
    """The cursor follows every role: right in n steps, hold, back in n steps."""
    kf = []
    for r, t0, t1, t2, t3 in segments:
        n, dx = len(r), len(r) * CW
        kf.append(f"{pct(t0)} {{ transform: translateX(0px); animation-timing-function: steps({n}, end); }}")
        kf.append(f"{pct(t1)} {{ transform: translateX({dx:.1f}px); animation-timing-function: linear; }}")
        kf.append(f"{pct(t2)} {{ transform: translateX({dx:.1f}px); animation-timing-function: steps({n}, end); }}")
        kf.append(f"{pct(t3)} {{ transform: translateX(0px); }}")
    kf.append("100% { transform: translateX(0px); }")
    return f"@keyframes cur {{ {' '.join(kf)} }}"


def main():
    name_b64 = base64.b64encode(open(sys.argv[1], "rb").read()).decode()
    roles_b64 = base64.b64encode(open(sys.argv[2], "rb").read()).decode()

    letters = "".join(
        f'<tspan class="ch" style="animation-delay:{0.15 + 0.07 * i:.2f}s">{c if c != " " else "&#160;"}</tspan>'
        for i, c in enumerate(NAME))
    role_css = "\n      ".join(role_keyframes(i, *seg) for i, seg in enumerate(segments))
    role_rules = " ".join(f".t{i} {{ animation: type{i} {CYCLE:.3f}s {START_S}s infinite; }}" for i in range(len(ROLES)))
    clips = "".join(
        f'<clipPath id="c{i}"><rect class="clip t{i}" x="{x_text:.1f}" y="{Y_TEXT - 22}" '
        f'width="{len(r) * CW:.1f}" height="30"/></clipPath>'
        for i, (r, *_) in enumerate(segments))
    texts = "".join(
        f'<text x="{x_text:.1f}" y="{Y_TEXT}" class="mono" clip-path="url(#c{i})">{r.replace("&", "&amp;")}</text>'
        for i, (r, *_) in enumerate(segments))

    print(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" width="{W}" height="{H}" role="img" aria-labelledby="t d">
  <title id="t">Yash Sawarkar</title>
  <desc id="d">Yash Sawarkar. {", ".join(ROLES).replace("&", "&amp;")}.</desc>
  <!-- Generated by tools/make-header.py; edit that, not this. -->
  <defs>
    <style>
      @font-face {{ font-family: "YS Display"; font-weight: 700; src: url(data:font/woff2;base64,{name_b64}) format("woff2"); }}
      @font-face {{ font-family: "YS Mono"; font-weight: 400; src: url(data:font/woff2;base64,{roles_b64}) format("woff2"); }}
      .name {{ font: 700 96px "YS Display", "Segoe UI", sans-serif; letter-spacing: -0.02em; fill: url(#aurora); }}
      .ch {{ opacity: 0; animation: ch .55s ease-out forwards; }}
      @keyframes ch {{ to {{ opacity: 1; }} }}
      .mono {{ font: 400 {FONT_PX}px "YS Mono", ui-monospace, monospace; fill: #cbd5e1; }}
      .prompt {{ fill: #2dd4bf; }}
      .clip {{ transform-box: fill-box; transform-origin: left; transform: scaleX(0); }}
      {role_css}
      {role_rules}
      .cur {{ animation: cur {CYCLE:.3f}s {START_S}s infinite; }}
      {cursor_keyframes()}
      .blink {{ animation: blink 1s steps(1) infinite; }}
      @keyframes blink {{ 50% {{ opacity: 0; }} }}
      .bar {{ transform-box: fill-box; transform-origin: center; transform: scaleX(0);
              animation: grow .8s cubic-bezier(.3,0,.2,1) 1.1s forwards; }}
      @keyframes grow {{ to {{ transform: scaleX(1); }} }}
      @media (prefers-reduced-motion: reduce) {{
        .ch, .bar {{ animation: none; opacity: 1; transform: none; }}
        .clip, .cur, .blink {{ animation: none; }}
        .t0 {{ transform: none; }}
        .cur {{ transform: translateX({len(ROLES[0]) * CW:.1f}px); }}
      }}
    </style>
    <pattern id="dots" width="22" height="22" patternUnits="userSpaceOnUse">
      <circle cx="1.5" cy="1.5" r="1.1" fill="#94a3b8" fill-opacity=".22"/>
    </pattern>
    <radialGradient id="fade" cx=".5" cy=".45" r=".62"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#000"/></radialGradient>
    <mask id="dotmask"><rect width="{W}" height="{H}" fill="url(#fade)"/></mask>
    <radialGradient id="glow" cx=".5" cy=".42" r=".5">
      <stop offset="0" stop-color="#2dd4bf" stop-opacity=".10"/>
      <stop offset=".6" stop-color="#818cf8" stop-opacity=".05"/>
      <stop offset="1" stop-color="#818cf8" stop-opacity="0"/>
    </radialGradient>
    <linearGradient id="accent" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0" stop-color="#2dd4bf"/><stop offset="1" stop-color="#818cf8"/>
    </linearGradient>
    <!-- The aurora: a wide repeating gradient sliding across the name. -->
    <linearGradient id="aurora" gradientUnits="userSpaceOnUse" x1="0" y1="0" x2="1200" y2="0" spreadMethod="repeat">
      <stop offset="0" stop-color="#e6edf3"/>
      <stop offset=".25" stop-color="#5eead4"/>
      <stop offset=".5" stop-color="#a5b4fc"/>
      <stop offset=".75" stop-color="#f0abfc"/>
      <stop offset="1" stop-color="#e6edf3"/>
      <animateTransform attributeName="gradientTransform" type="translate" from="0 0" to="1200 0" dur="9s" repeatCount="indefinite"/>
    </linearGradient>
    {clips}
  </defs>

  <rect width="{W}" height="{H}" rx="20" fill="#0b0f17"/>
  <rect width="{W}" height="{H}" rx="20" fill="url(#dots)" mask="url(#dotmask)"/>
  <rect width="{W}" height="{H}" rx="20" fill="url(#glow)"/>
  <rect x=".5" y=".5" width="{W - 1}" height="{H - 1}" rx="19.5" fill="none" stroke="#94a3b8" stroke-opacity=".12"/>

  <text x="{W / 2}" y="150" text-anchor="middle" class="name">{letters}</text>
  <rect class="bar" x="{W / 2 - 40}" y="178" width="80" height="4" rx="2" fill="url(#accent)"/>

  <text x="{x_prompt:.1f}" y="{Y_TEXT}" class="mono prompt">&gt;</text>
  {texts}
  <g class="blink"><rect class="cur" x="{x_text + 2:.1f}" y="{Y_TEXT - 17}" width="11" height="21" rx="1.5" fill="#818cf8"/></g>
</svg>''')


if __name__ == "__main__":
    main()
